#!/bin/sh
echo "\033[;32m"\\nHotPi-QMI will now be installed on your system.\\n\\nPress "\033[;37m"ENTER"\033[;32m" to continue...
read hotpips
apt update
apt upgrade -y
apt install bridge-utils dnsmasq hostapd libqmi-utils ppp resolvconf samba udhcpc xrdp -y
echo \#!/bin/sh\\necho \"\\nHotPi-QMI \(USB - 150 Mbps\)\\n\\n\\nCommand List:\\n\\n\\nsudo hotpi-help - View command list\\n\\nsudo hotpi-setwifi - Set Wi-Fi settings\\n\\nsudo hotpi-startqmi - Start QMI connection\\n\\nsudo hotpi-stopqmi - Stop QMI connection\\n\" > /bin/hotpi-help
echo \#!/bin/sh\\necho '"\\033[;32m"\\\\nEnter your Wi-Fi country code:\\\\n'\\necho Canada: CA\\necho United Kingdom: UK\\necho United States: US'\\\\n'\\nread hotpicc\\necho '\\\\nWi-Fi country code set to "\\033[;37m"$hotpicc"\\033[;32m"'.\\necho '\\\\nCreate your Wi-Fi network name:\\\\n'\\nread hotpinn\\necho '\\\\nWi-Fi network name set to "\\033[;37m"$hotpinn"\\033[;32m"'.\\necho '\\\\nCreate your Wi-Fi network password:\\\\n'\\nread hotpinp\\necho '\\\\nWi-Fi network password set to "\\033[;37m"$hotpinp"\\033[;32m"'.\\necho '\\\\nTo change these settings, use the "\\033[;37m"sudo hotpi-setwifi"\\033[;32m"' command.\\necho '\\\\nPress "\\033[;37m"ENTER"\\033[;32m"' to continue...\\nread hotpips\\necho \"interface=wlan0\\nbridge=br0\\ncountry_code=\$hotpicc\\nieee80211ac=1\\nwmm_enabled=1\\nhw_mode=a\\nchannel=36\\nht_capab=[HT40+]\\nssid=\$hotpinn\\nwpa_passphrase=\$hotpinp\\nwpa=2\\nwpa_key_mgmt=WPA-PSK\\nrsn_pairwise=CCMP\" \> /etc/hostapd/hostapd.conf > /bin/hotpi-setwifi
echo \#!/bin/sh\\necho\\nifconfig wwan0 down\\necho Y \> /sys/class/net/wwan0/qmi/raw_ip\\nqmicli -d /dev/cdc-wdm0 --dms-set-operating-mode=online\\nqmicli -d /dev/cdc-wdm0 -p --wds-start-network=ip-type=4 --client-no-release-cid '&& udhcpc -i wwan0 && echo \\\\n'The QMI connection has been started.\\necho > /bin/hotpi-startqmi
echo \#!/bin/sh\\necho\\nifconfig wwan0 down \&\& echo The QMI connection has been stopped.\\necho > /bin/hotpi-stopqmi
chmod 755 /bin/hotpi-help /bin/hotpi-setwifi /bin/hotpi-startqmi /bin/hotpi-stopqmi
stty -F /dev/ttyUSB2 115200
chat '' at+qcfg='"usbnet"',0 OK > /dev/ttyUSB2 < /dev/ttyUSB2
hotpi-setwifi
sed -i -e /allow-hotplug\ br0/d -e /iface\ br0\ inet\ static/d -e /address\ 192.168.0.1/d -e /bridge_ports\ wlan0\ eth0/d /etc/network/interfaces
echo allow-hotplug br0\\niface br0 inet static\\naddress 192.168.0.1\\nbridge_ports wlan0 eth0 >> /etc/network/interfaces
sed -i -e /interface=br0/d -e /dhcp-range=192.168.0.2,192.168.0.10,24h/d /etc/dnsmasq.conf
echo interface=br0\\ndhcp-range=192.168.0.2,192.168.0.10,24h >> /etc/dnsmasq.conf
sed -i s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/ /etc/sysctl.conf
iptables -t nat -F
iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE
iptables-save > /etc/hotpi-iptables
sed -i -e /\\[External\ Storage]/d -e /path\ =\ \\/media\\/pi/d -e /public\ =\ yes/d -e /writeable\ =\ yes/d /etc/samba/smb.conf
echo [External Storage]\\npath = /media/pi\\npublic = yes\\nwriteable = yes >> /etc/samba/smb.conf
mkdir -p /media/pi
chmod -R 777 /media/pi
sed -i -e /iptables-restore\ \<\ \\/etc\\/hotpi-iptables/d -e /hotpi-startqmi/d -e s/^exit\ 0/iptables-restore\ \<\ \\/etc\\/hotpi-iptables\\nhotpi-startqmi\\nexit\ 0/ /etc/rc.local
systemctl unmask hostapd
systemctl enable hostapd resolvconf
echo \\nHotPi-QMI has been successfully installed on your system.\\n\\nFor a command list, use the "\033[;37m"sudo hotpi-help"\033[;32m" command.\\n\\nPress "\033[;37m"ENTER"\033[;32m" to reboot...
read hotpips
reboot
