#!/bin/sh

############################################################################################################################################################

# PACKAGE MANAGEMENT

apt update && apt upgrade -y
apt install bridge-utils dnsmasq hostapd ifupdown iptables libqmi-utils resolvconf samba udhcpc udiskie udisks2 xrdp -y
apt purge dhcpcd modemmanager -y

############################################################################################################################################################

# USER COMMANDS

	# START DATA CONNECTION

echo '#!/bin/sh
sudo qmicli -d /dev/cdc-wdm0 -E raw-ip
sudo qmicli -d /dev/cdc-wdm0 --wds-start-network=ip-type=4 --client-no-release-cid
sudo udhcpc -i wwan0' > /bin/hotpistart

	# STOP DATA CONNECTION

echo '#!/bin/sh
sudo ifconfig wwan0 down' > /bin/hotpistop

	# MOUNT USB STORAGE

echo '#!/bin/sh
sudo udisksctl mount -b /dev/$1' > /bin/hotpimount

	# UNMOUNT USB STORAGE

echo '#!/bin/sh
sudo udisksctl unmount -b /dev/$1' > /bin/hotpiunmount

############################################################################################################################################################

# NETWORK SETTINGS

	# NETWORK BRIDGE

		# GATEWAY NODE

sed -i /allow-hotplug\ br0/,+3d /etc/network/interfaces
echo 'allow-hotplug br0
iface br0 inet static
address 192.168.0.1
bridge_ports wlan0 eth0' >> /etc/network/interfaces

		# DHCP SERVER

sed -i /interface=br0/,+1d /etc/dnsmasq.conf
echo 'interface=br0
dhcp-range=192.168.0.2,192.168.0.254,24h' >> /etc/dnsmasq.conf

		# PACKET FORWARDING

sed -i /^net.ipv4.ip_forward=1/d /etc/sysctl.conf
echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf

		# PACKET FILTERING

iptables -t nat -F
iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE
iptables-save > /etc/hotpifilter

	# WI-FI NETWORK

echo 'interface=wlan0
bridge=br0
ieee80211ac=1
channel=36
hw_mode=a
ht_capab=[HT40+]
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
country_code=US
ssid=RPI-5G
wpa_passphrase=passphrase' > /etc/hostapd/hostapd.conf

	# NETWORK-ATTACHED STORAGE

sed -i /\\[USB\ Storage]/,+3d /etc/samba/smb.conf
echo '[USB Storage]
path = /media/root
public = yes
writeable = yes' >> /etc/samba/smb.conf

############################################################################################################################################################

# POWER SETTINGS

	# USB PORTS

sed -i /usb_max_current_enable=1/d /boot/firmware/config.txt
echo usb_max_current_enable=1 >> /boot/firmware/config.txt

	# PWM FAN

sed -i /dtparam=fan_temp0=45000/,+8d /boot/firmware/config.txt
echo 'dtparam=fan_temp0=45000
dtparam=fan_temp0_hyst=5000
dtparam=fan_temp0_speed=125
dtparam=fan_temp1=50000
dtparam=fan_temp1_hyst=10000
dtparam=fan_temp1_speed=190
dtparam=fan_temp2=55000
dtparam=fan_temp2_hyst=15000
dtparam=fan_temp2_speed=255' >> /boot/firmware/config.txt

############################################################################################################################################################

# AUTOMATION

	# DATA CONNECTION

echo 'ATTR{idVendor}=="1e0e", ATTR{idProduct}=="9001", RUN="/bin/systemctl start hotpistart"' > /etc/udev/rules.d/hotpistart.rules
echo '[Service]
ExecStart=hotpistart' > /etc/systemd/system/hotpistart.service

	# PACKET FILTERING

echo "[Service]
ExecStart=sh -c 'iptables-restore < /etc/hotpifilter'
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/hotpifilter.service

	# USB STORAGE MOUNTING

echo '[Service]
ExecStart=udiskie -N -F
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/hotpimount.service

############################################################################################################################################################

# EXECUTION

mkdir -p /media/root
chmod 755 /bin/hotpi* /media/root
systemctl unmask hostapd
systemctl enable hostapd hotpifilter hotpimount resolvconf
reboot

############################################################################################################################################################
