#!/bin/sh

echo HotPi Pro Lite is being installed...

apt update && sudo apt upgrade -y
apt install bridge-utils dnsmasq hostapd ifupdown iptables libqmi-utils resolvconf samba udhcpc udiskie udisks2 xrdp -y

echo '#!/bin/sh
echo Enter Wi-Fi country code:
read var
sudo sed -i /country_code=.*/d /etc/hostapd/hostapd.conf
sudo sh -c "echo country_code=$var >> /etc/hostapd/hostapd.conf"' > /bin/hotpiwc

echo '#!/bin/sh
echo Create Wi-Fi name:
read var
sudo sed -i /ssid=.*/d /etc/hostapd/hostapd.conf
sudo sh -c "echo ssid=$var >> /etc/hostapd/hostapd.conf"' > /bin/hotpiwn

echo '#!/bin/sh
echo Create Wi-Fi password:
read var
sudo sed -i /wpa_passphrase=.*/d /etc/hostapd/hostapd.conf
sudo sh -c "echo wpa_passphrase=$var >> /etc/hostapd/hostapd.conf"' > /bin/hotpiwp

echo '#!/bin/sh
sudo qmicli -d /dev/cdc-wdm0 --dms-set-operating-mode=online
sudo qmicli -d /dev/cdc-wdm0 -E raw-ip
sudo qmicli -d /dev/cdc-wdm0 -p --wds-start-network=ip-type=4 --client-no-release-cid
sudo udhcpc -i wwan0' > /bin/hotpiec

echo '#!/bin/sh
sudo ifconfig wwan0 down' > /bin/hotpitc

echo '#!/bin/sh
echo Enter storage device name:
read var
udisksctl mount -b /dev/$var' > /bin/hotpims

echo '#!/bin/sh
echo Enter storage device name:
read var
udisksctl unmount -b /dev/$var' > /bin/hotpius

echo '#!/bin/sh
echo "COMMAND               DESCRIPTION
hotpiwc               Set Wi-Fi Country Code
hotpiwn               Set Wi-Fi Name
hotpiwp               Set Wi-Fi Password
hotpiec               Establish Data Connection
hotpitc               Terminate Data Connection
hotpims               Mount Storage Device
hotpius               Unmount Storage Device
hotpicl               View Command List"' > /bin/hotpicl

chmod -R 777 /bin/hotpi*

sed -i -e /allow-hotplug\ br0/d -e /iface\ br0\ inet\ static/d -e /address\ 192.168.0.1/d -e /bridge_ports\ wlan0\ eth0/d /etc/network/interfaces
echo 'allow-hotplug br0
iface br0 inet static
address 192.168.0.1
bridge_ports wlan0 eth0' >> /etc/network/interfaces

sed -i -e /interface=br0/d -e /dhcp-range=192.168.0.2,192.168.0.254,24h/d /etc/dnsmasq.conf
echo 'interface=br0
dhcp-range=192.168.0.2,192.168.0.254,24h' >> /etc/dnsmasq.conf

sed -i /^net.ipv4.ip_forward=1/d /etc/sysctl.conf
echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf

iptables -t nat -F
iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE
iptables-save > /etc/hotpitables

echo 'interface=wlan0
bridge=br0
ieee80211ac=1
channel=36
hw_mode=a
ht_capab=[HT40+]
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP' > /etc/hostapd/hostapd.conf

echo 'sudo sed -i '"'"'/\[USB Storage]/,$d'"'"' /etc/samba/smb.conf
sudo sh -c "echo '"'"'[USB Storage]
path = /media/$USER
public = yes
writeable = yes'"'"' >> /etc/samba/smb.conf"
sudo mkdir -p /media/$USER
sudo chmod -R 777 /media/$USER' > /etc/profile.d/hotpisamba.sh

sed -i -e /dtoverlay=gpio-shutdown,debounce=1000/d -e /usb_max_current_enable=1/d /boot/firmware/config.txt
echo 'dtoverlay=gpio-shutdown,debounce=1000
usb_max_current_enable=1' >> /boot/firmware/config.txt

echo '[Service]
ExecStart=hotpiec' > /etc/systemd/system/hotpistart.service
echo 'ATTR{idVendor}=="1e0e", ATTR{idProduct}=="9001", RUN="/bin/systemctl start hotpistart"
ATTR{idVendor}=="2c7c", ATTR{idProduct}=="0125", RUN="/bin/systemctl start hotpistart"' > /etc/udev/rules.d/hotpistart.rules

echo '[Service]
ExecStart=sh -c '"'"'iptables-restore < /etc/hotpitables'"'"'
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/hotpitables.service

echo '[Service]
ExecStart=udiskie -N -F' > /etc/systemd/user/hotpimount.service
echo systemctl --user start hotpimount > /etc/profile.d/hotpimount.sh

sed -i -e 87s/auth_admin/yes/ -e 89s/auth_admin_keep/yes/ /usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy

hotpiwc
hotpiwn
hotpiwp
systemctl unmask hostapd
systemctl enable hostapd hotpitables resolvconf

echo "HotPi Pro Lite has been installed...
Press ENTER to reboot:"
read var
reboot
