#!/bin/sh
echo HotPi-QMI will now be installed on your system.\\nPress "\033[;36m"ENTER"\e[0m" to continue...
read hotpips
apt update
apt upgrade -y
apt install bridge-utils dnsmasq hostapd libqmi-utils resolvconf samba udhcpc xrdp -y
sed -i -e /allow-hotplug\ br0/d -e /iface\ br0\ inet\ static/d -e /address\ 192.168.0.1/d -e /bridge_ports\ wlan0\ eth0/d /etc/network/interfaces -e /interface=br0/d -e /dhcp-range=192.168.0.2,192.168.0.10,24h/d /etc/dnsmasq.conf -e s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/ /etc/sysctl.conf -e /\\[External\ Storage]/d -e /path\ =\ \\/media\\/pi/d -e /public\ =\ yes/d -e /writeable\ =\ yes/d /etc/samba/smb.conf -e /iptables-restore\ \<\ \\/etc\\/hotpi-tables/d -e /hotpi-start/d -e s/^exit\ 0/iptables-restore\ \<\ \\/etc\\/hotpi-tables\\nhotpi-start\\nexit\ 0/ /etc/rc.local
echo \#!/bin/sh\\necho \"sudo hotpi-help - View Command List\\nsudo hotpi-wifi - Set Wi-Fi Settings\\nsudo hotpi-start - Start QMI Connection\\nsudo hotpi-stop - Stop QMI Connection\" > /bin/hotpi-help
echo \#!/bin/sh\\necho Enter your Wi-Fi country code:\\nread hotpicc\\necho Wi-Fi country code set to: '"\\033[;36m"$hotpicc"\\e[0m"\\\\n'Create your Wi-Fi network name:\\nread hotpinn\\necho Wi-Fi network name set to: '"\\033[;36m"$hotpinn"\\e[0m"\\\\n'Create your Wi-Fi network password:\\nread hotpinp\\necho Wi-Fi network password set to: '"\\033[;36m"$hotpinp"\\e[0m"'\\necho \"interface=wlan0\\nbridge=br0\\ncountry_code=\$hotpicc\\nieee80211ac=1\\nwmm_enabled=1\\nhw_mode=a\\nchannel=36\\nht_capab=[HT40+]\\nssid=\$hotpinn\\nwpa_passphrase=\$hotpinp\\nwpa=2\\nwpa_key_mgmt=WPA-PSK\\nrsn_pairwise=CCMP\" \> /etc/hostapd/hostapd.conf > /bin/hotpi-wifi
echo \#!/bin/sh\\nqmicli -d /dev/cdc-wdm0 --dms-set-operating-mode=online\\nqmicli -d /dev/cdc-wdm0 -E raw-ip '&& qmicli -d /dev/cdc-wdm0 -p --wds-start-network=ip-type=4 --client-no-release-cid && udhcpc -i wwan0 &&' echo The QMI connection has been established. > /bin/hotpi-start
echo \#!/bin/sh\\nifconfig wwan0 down \&\& echo The QMI connection has been terminated. > /bin/hotpi-stop
echo allow-hotplug br0\\niface br0 inet static\\naddress 192.168.0.1\\nbridge_ports wlan0 eth0 >> /etc/network/interfaces
echo interface=br0\\ndhcp-range=192.168.0.2,192.168.0.10,24h >> /etc/dnsmasq.conf
echo [External Storage]\\npath = /media/pi\\npublic = yes\\nwriteable = yes >> /etc/samba/smb.conf
mkdir -p /media/pi
chmod 755 /bin/hotpi-* /media/pi
hotpi-wifi
iptables -t nat -F
iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE
iptables-save > /etc/hotpi-tables
systemctl unmask hostapd
systemctl enable hostapd resolvconf
echo HotPi-QMI has been installed successfully.\\nUse "\033[;36m"sudo hotpi-help"\e[0m" for a command list.\\nPress "\033[;36m"ENTER"\e[0m" to reboot...
read hotpips
reboot
