#!/bin/sh
apt update
apt upgrade -y
apt install bridge-utils dnsmasq hostapd ppp resolvconf samba xrdp -y
echo \#!/bin/sh\\necho \"sudo hotpi-help - View Command List\\nsudo hotpi-setwifi - Set Wi-Fi Settings\\nsudo hotpi-startppp - Start PPP Connection\\nsudo hotpi-stopppp - Stop PPP Connection\" > /bin/hotpi-help
echo \#!/bin/sh\\necho '\\\\nEnter your current modem baud rate:\\\\n\\\\nDefault: 115200\\\\n'\\nread hotpibr\\nif '[ $hotpibr = 9600 ] || [ $hotpibr = 19200 ] || [ $hotpibr = 38400 ] || [ $hotpibr = 57600 ] || [ $hotpibr = 115200 ] || [ $hotpibr = 230400 ] || [ $hotpibr = 460800 ] || [ $hotpibr = 921600 ] || [ $hotpibr = 1500000 ] || [ $hotpibr = 2000000 ] || [ $hotpibr = 2500000 ]'\\nthen\\necho '\\\\nMaximizing modem baud rate...\\\\n\\\\nModem baud rate set to: "\\033[;36m"3000000"\\e[0m"'\\nelif '[ $hotpibr = 3000000 ]'\\nthen\\necho '\\\\nModem baud rate set to: "\\033[;36m"3000000"\\e[0m"'\\nelse\\necho '\\\\n'Invalid modem baud rate...\\nhotpi-setbaud\\nexit\\nfi\\necho '\\\\nYour modem baud rate has been configured successfully.\\\\n\\\\nPress "\\033[;36m"ENTER"\\e[0m"' to continue...\\nread hotpips\\necho '$hotpibr >' /etc/hotpi-baudrate > /bin/hotpi-setbaud
echo \#!/bin/sh\\necho Enter your Wi-Fi country code:'\\\\n\\\\nCanada: CA\\\\nUnited Kingdom: UK\\\\nUnited States: US\\\\n'\\nread hotpicc\\necho '\\\\nWi-Fi country code set to: "\\033[;36m"$hotpicc"\\e[0m"\\\\n\\\\nCreate your Wi-Fi network name:\\\\n'\\nread hotpinn\\necho '\\\\nWi-Fi network name set to: "\\033[;36m"$hotpinn"\\e[0m"\\\\n\\\\nCreate your Wi-Fi network password:\\\\n'\\nread hotpinp\\necho '\\\\nWi-Fi network password set to: "\\033[;36m"$hotpinp"\\e[0m"\\\\n\\\\nYour Wi-Fi network has been configured successfully.\\\\n\\\\nUse "\\033[;36m"sudo hotpi-setwifi"\\e[0m" to change these settings.\\\\n\\\\nPress "\\033[;36m"ENTER"\\e[0m"' to continue...\\nread hotpips\\necho \"interface=wlan0\\nbridge=br0\\ncountry_code=\$hotpicc\\nieee80211ac=1\\nwmm_enabled=1\\nhw_mode=a\\nchannel=36\\nht_capab=[HT40+]\\nssid=\$hotpinn\\nwpa_passphrase=\$hotpinp\\nwpa=2\\nwpa_key_mgmt=WPA-PSK\\nrsn_pairwise=CCMP\" \> /etc/hostapd/hostapd.conf > /bin/hotpi-setwifi
echo \#!/bin/sh\\npppd connect '"'chat "''" atd*99#'"' /dev/ttyAMA0 crtscts 3000000 :10.64.64.64 usepeerdns defaultroute noauth persist updetach \&\& echo The PPP connection has been established. > /bin/hotpi-startppp
echo \#!/bin/sh\\npoff -a \&\& echo The PPP connection has been terminated. > /bin/hotpi-stopppp
chmod 755 /bin/hotpi-help /bin/hotpi-setbaud /bin/hotpi-setwifi /bin/hotpi-startppp /bin/hotpi-stopppp
hotpi-setbaud
hotpi-setwifi
sed -i s/console=serial0,115200\ // /boot/cmdline.txt
sed -i /dtoverlay=pi3-disable-bt/d /boot/config.txt
echo dtoverlay=pi3-disable-bt >> /boot/config.txt
sed -i -e /allow-hotplug\ br0/d -e /iface\ br0\ inet\ static/d -e /address\ 192.168.0.1/d -e /bridge_ports\ wlan0\ eth0/d /etc/network/interfaces
echo allow-hotplug br0\\niface br0 inet static\\naddress 192.168.0.1\\nbridge_ports wlan0 eth0 >> /etc/network/interfaces
sed -i -e /interface=br0/d -e /dhcp-range=192.168.0.2,192.168.0.10,24h/d /etc/dnsmasq.conf
echo interface=br0\\ndhcp-range=192.168.0.2,192.168.0.10,24h >> /etc/dnsmasq.conf
sed -i s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/ /etc/sysctl.conf
iptables -t nat -F
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
iptables-save > /etc/hotpi-iptables
sed -i -e /\\[External\ Storage]/d -e /path\ =\ \\/media\\/pi/d -e /public\ =\ yes/d -e /writeable\ =\ yes/d /etc/samba/smb.conf
echo [External Storage]\\npath = /media/pi\\npublic = yes\\nwriteable = yes >> /etc/samba/smb.conf
mkdir -p /media/pi
chmod -R 777 /media/pi
sed -i -e /iptables-restore\ \<\ \\/etc\\/hotpi-iptables/d -e /hotpi-startppp/d -e s/^exit\ 0/iptables-restore\ \<\ \\/etc\\/hotpi-iptables\\ntail\ -n\ +34\ \\/bin\\/hotpi-installppp\ \|\ sh\\nexit\ 0/ /etc/rc.local
systemctl unmask hostapd
systemctl enable hostapd resolvconf
echo \\nHotPi-PPP has been installed successfully.\\n\\nUse "\033[;36m"sudo hotpi-help"\e[0m" for a command list.\\n\\nPress "\033[;36m"ENTER"\e[0m" to reboot...
read hotpips
reboot
stty -F /dev/ttyAMA0 $(cat /etc/hotpi-baudrate)
chat '' at+cgdcont=1,'"ipv4v6"' OK at+iprex=3000000 OK > /dev/ttyAMA0 < /dev/ttyAMA0
hotpi-startppp
sed -i s/tail\ -n\ +34\ \\/bin\\/hotpi-installppp\ \|\ sh/hotpi-startppp/ /etc/rc.local
