#!/bin/sh

echo '#!/bin/sh
echo Enter Wi-Fi country code:
read var
sudo sed -i /country_code=.*/d /etc/hostapd/hostapd.conf
sudo sh -c "echo country_code=$var >> /etc/hostapd/hostapd.conf"' > /bin/hotpicode

echo '#!/bin/sh
echo Create Wi-Fi network name:
read var
sudo sed -i /ssid=.*/d /etc/hostapd/hostapd.conf
sudo sh -c "echo ssid=$var >> /etc/hostapd/hostapd.conf"' > /bin/hotpiname

echo '#!/bin/sh
echo Create Wi-Fi network password:
read var
sudo sed -i /wpa_passphrase=.*/d /etc/hostapd/hostapd.conf
sudo sh -c "echo wpa_passphrase=$var >> /etc/hostapd/hostapd.conf"' > /bin/hotpipassword

echo '#!/bin/sh
sudo qmicli -d /dev/cdc-wdm0 -E raw-ip
sudo qmicli -d /dev/cdc-wdm0 --wds-start-network=ip-type=4 --client-no-release-cid
sudo udhcpc -i wwan0' > /bin/hotpistart

echo '#!/bin/sh
sudo ifconfig wwan0 down' > /bin/hotpistop

echo '#!/bin/sh
echo Enter storage device name:
read var
sudo udisksctl mount -b /dev/$var' > /bin/hotpimount

echo '#!/bin/sh
echo Enter storage device name:
read var
sudo udisksctl unmount -b /dev/$var' > /bin/hotpiunmount

echo '#!/bin/sh
sudo reboot' > /bin/hotpireboot

echo '#!/bin/sh
sudo shutdown now' > /bin/hotpishutdown

echo '#!/bin/sh
echo "COMMAND                 DESCRIPTION
hotpicode               Set Wi-Fi Country Code
hotpiname               Set Wi-Fi Network Name
hotpipassword           Set Wi-Fi Network Password
hotpistart              Establish Data Connection
hotpistop               Terminate Data Connection
hotpimount              Mount Storage Device
hotpiunmount            Unmount Storage Device
hotpireboot             Reboot Raspberry Pi
hotpishutdown           Shutdown Raspberry Pi
hotpihelp               View User Command List"' > /bin/hotpihelp

sed -i '/allow-hotplug br0/,$d' /etc/network/interfaces
echo 'allow-hotplug br0
iface br0 inet static
address 192.168.0.1
bridge_ports wlan0 eth0' >> /etc/network/interfaces

sed -i '/interface=br0/,$d' /etc/dnsmasq.conf
echo 'interface=br0
dhcp-range=192.168.0.2,192.168.0.254,24h' >> /etc/dnsmasq.conf

sed -i /^net.ipv4.ip_forward=1/d /etc/sysctl.conf
echo net.ipv4.ip_forward=1 >> /etc/sysctl.conf

echo 'interface=wlan0
bridge=br0
ieee80211ac=1
channel=36
hw_mode=a
ht_capab=[HT40+]
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP' > /etc/hostapd/hostapd.conf

sed -i '/\[USB Storage]/,$d' /etc/samba/smb.conf
echo '[USB Storage]
path = /media/root
public = yes
writeable = yes' >> /etc/samba/smb.conf

sed -i /usb_max_current_enable=1/d /boot/firmware/config.txt
echo usb_max_current_enable=1 >> /boot/firmware/config.txt

echo 'ATTR{idVendor}=="1e0e", ATTR{idProduct}=="9001", RUN="/bin/systemctl start hotpistart"
ATTR{idVendor}=="2c7c", ATTR{idProduct}=="0125", RUN="/bin/systemctl start hotpistart"' > /etc/udev/rules.d/hotpistart.rules

echo '[Service]
ExecStart=hotpistart' > /etc/systemd/system/hotpistart.service

echo "[Service]
ExecStart=sh -c 'iptables-restore < /etc/hotpitables'
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/hotpitables.service

echo '[Service]
ExecStart=udiskie -N -F
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/hotpimount.service

apt update && apt upgrade -y
apt install bridge-utils dnsmasq hostapd ifupdown iptables libqmi-utils resolvconf samba udhcpc udiskie udisks2 xrdp -y
apt purge dhcpcd modemmanager -y
iptables -t nat -F
iptables -t nat -A POSTROUTING -o wwan0 -j MASQUERADE
iptables-save > /etc/hotpitables
mkdir -p /media/root
chmod 755 /bin/hotpi* /media/root
hotpicode
hotpiname
hotpipassword
systemctl unmask hostapd
systemctl enable hostapd hotpimount hotpitables resolvconf
reboot
